import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { LayoutDashboard, Users, Stethoscope, Heart, CalendarDays, DoorOpen, Activity } from 'lucide-react';
export default function Sidebar({ className = 'hidden md:flex' }) {
    return (_jsxs("aside", { className: `fixed top-0 left-0 bg-black/40 backdrop-blur-xl border-r border-white/8 flex-col h-screen w-[220px] flex-shrink-0 z-40 ${className}`, children: [_jsxs("div", { className: "px-5 py-5 border-b border-white/8 flex items-center gap-3", children: [_jsxs("svg", { width: "28", height: "28", viewBox: "0 0 28 28", className: "flex-shrink-0", children: [_jsx("rect", { width: "28", height: "28", rx: "8", fill: "currentColor", opacity: "0.12", className: "text-teal-400" }), _jsx("path", { d: "M14 7v14M7 14h14", stroke: "#4f98a3", strokeWidth: "2.5", strokeLinecap: "round" })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-sm font-bold text-white leading-tight", children: "MediCore HMS" }), _jsx("span", { className: "text-xs text-white/40 leading-tight", children: "Hospital Management" })] })] }), _jsxs("nav", { className: "flex-1 px-3 py-4 flex flex-col gap-1 overflow-y-auto", children: [_jsx("div", { className: "text-[10px] font-semibold text-white/25 uppercase tracking-wider px-2 py-2 mt-2", children: "Overview" }), _jsx(NavLink, { to: "/", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(LayoutDashboard, { className: "w-4 h-4 flex-shrink-0" }), "Dashboard"] })) }), _jsx("div", { className: "text-[10px] font-semibold text-white/25 uppercase tracking-wider px-2 py-2 mt-2", children: "People" }), _jsx(NavLink, { to: "/patients", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(Users, { className: "w-4 h-4 flex-shrink-0" }), "Patients"] })) }), _jsx(NavLink, { to: "/doctors", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(Stethoscope, { className: "w-4 h-4 flex-shrink-0" }), "Doctors"] })) }), _jsx(NavLink, { to: "/nurses", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(Heart, { className: "w-4 h-4 flex-shrink-0" }), "Nurses"] })) }), _jsx("div", { className: "text-[10px] font-semibold text-white/25 uppercase tracking-wider px-2 py-2 mt-2", children: "Operations" }), _jsx(NavLink, { to: "/appointments", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(CalendarDays, { className: "w-4 h-4 flex-shrink-0" }), "Appointments"] })) }), _jsx(NavLink, { to: "/rooms", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(DoorOpen, { className: "w-4 h-4 flex-shrink-0" }), "Rooms"] })) }), _jsx("div", { className: "text-[10px] font-semibold text-white/25 uppercase tracking-wider px-2 py-2 mt-2", children: "Records" }), _jsx(NavLink, { to: "/activity", className: ({ isActive }) => `relative flex items-center gap-3 px-3 py-2 rounded-xl text-sm font-medium transition-all ${isActive
                            ? 'text-teal-300 bg-teal-500/10 hover:bg-teal-500/15'
                            : 'text-white/50 hover:text-white hover:bg-white/5'}`, children: ({ isActive }) => (_jsxs(_Fragment, { children: [isActive && _jsx("div", { className: "absolute left-0 w-0.5 h-4 bg-teal-400 rounded-full animate-[scaleY_200ms_ease_forwards] origin-center" }), _jsx(Activity, { className: "w-4 h-4 flex-shrink-0" }), "Activity Log"] })) })] })] }));
}
